version: '3.6'

services:

  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - ./appdata:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - "8200:5005"
    environment:
      - PASSWORD=p4ssw0rd 
    restart: unless-stopped

    

